### ISSUE TITLE
Add access to LogEvent properties in getMixedFields method

### ISSUE THREAD

**Issue by MKhabrat** [tomilaurell/log4j2-extended-jsonlayout#1]
Hello!

Thank you for continuing the work on the library.

In our project, when forming the map of mixed fields it is sometimes nessessary to access `LogEvent` properties like `level` or `instant`, but currently it is not possible, because `getMixedFields` of `ExtendedJson` class receive `Message` as a parameter.

Is it possible to add functionality so the `getMixedFields` method could make use of `LogEvent`'s properties?

**Comment by tomilaurell** [comment]
Hi,

Actually that was the main reason I did this. The updated example shows:
´´´
import org.apache.logging.log4j.message.Message
@Override
public Map<String, Object> getMixedFields(Message message) {
	return mixedIn;
}
´´´
which means that it can access anything in the message.

**Comment by tomilaurell** [comment]
Hi,
I'll check how this can be done. I first though that it should be possible already.

**Comment by tomilaurell** [comment]
Good suggestion and release made with the version 1.0.4
I also added example repository https://github.com/tomilaurell/log4j2-extended-jsonlayout-example
